language: go
sudo: false

matrix:
  include:
  - go: 1.9.x
  - go: 1.10.x
  - go: 1.11.x
  - go: tip
  allow_failures:
  - go: tip

script:
- go test -race ./...
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install --update
- gometalinter ./...